**Task 1: Create a list of following: 2, 6, 11, 24, 8, 45, 25, 60**

In [14]:
my_list = [2, 6, 11, 24, 8, 45, 25, 60]
print(my_list)

my_list = my_list[:-1]
# b) Add 22 value at index 3 of the list
my_list.insert(3, 22)

# c) Create an ndarray object using this list
import numpy as np
my_array = np.array(my_list)


[2, 6, 11, 24, 8, 45, 25, 60]


**Delete last element of the list**

In [12]:
my_list = [2, 6, 11, 24, 8, 45, 25, 60]
my_list = my_list[:-1]
print(my_list)

[2, 6, 11, 24, 8, 45, 25]


**Add 22 value at index 3 of the list**

In [11]:
my_list = [2, 6, 11, 24, 8, 45, 25, 60]
my_list.insert(3, 22)
print(my_list)

[2, 6, 11, 22, 24, 8, 45, 25, 60]


**Create an ndarray object using this list**

In [15]:
import numpy as np
my_list = [2, 6, 11, 24, 8, 45, 25, 60]
my_array = np.array(my_list)
print(my_array)

[ 2  6 11 24  8 45 25 60]


**Task 2: Create a 2-D array and a 3-D array. Split the 2-D array into three 2-D arrays along rows.**

In [33]:
import numpy as np

my_2d_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

my_3d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

split_arrays = np.split(my_2d_array, 3, axis=0)

print("\nOriginal 2-D Array:")
print(my_2d_array)
print("\nOriginal 3-D Array:")
print(my_3d_array)

for index, array in enumerate(split_arrays):
    print(f"\nSplit Array {index + 1}:\n{array}")



Original 2-D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Original 3-D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Split Array 1:
[[10 20 30]]

Split Array 2:
[[40 50 60]]

Split Array 3:
[[70 80 90]]


**Task 3: Find the indexes where the values are even**

In [32]:
even_indexes = np.where(my_2d_array % 2 == 0)
print(f"\nIndexes where values are even in the 2D array:\n{even_indexes}")


Indexes where values are even in the 2D array:
(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


**Task 4: Create a filter array that will return only values higher than 55**

In [31]:
filter_array = my_2d_array > 55
filtered_values = my_2d_array[filter_array]

print(f"\nValues higher than 55 in the 2D array:\n{filtered_values}")


Values higher than 55 in the 2D array:
[60 70 80 90]


**Task 5: Create a 3x3 matrix with values ranging from 2 to 10, convert the array to a float type. Write a Python program to find the maximum and minimum value of the flattened array.**

In [37]:
matrix_3x3 = np.arange(2, 11).reshape(3, 3)

print(f"\n3x3 Matrix with values ranging from 2 to 10:\n{matrix_3x3}")

matrix_3x3_float = matrix_3x3.astype(float)

print(f"\n3x3 Matrix converted to float type:\n{matrix_3x3_float}")

max_value = np.max(matrix_3x3_float)
min_value = np.min(matrix_3x3_float)

print(f"\nMaximum value of the flattened array: {max_value}")
print(f"Minimum value of the flattened array: {min_value}")



3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

3x3 Matrix converted to float type:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

Maximum value of the flattened array: 10.0
Minimum value of the flattened array: 2.0
